global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # MIB Platform Backend
  - job_name: 'mib-backend'
    static_configs:
      - targets: ['mib-backend:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # SNMP Exporter
  - job_name: 'snmp-exporter'
    static_configs:
      - targets: ['snmp-exporter:9116']
    scrape_interval: 30s

  # VictoriaMetrics
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
    scrape_interval: 30s

  # VMAgent 自身
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
    scrape_interval: 30s

  # VMAlert
  - job_name: 'vmalert'
    static_configs:
      - targets: ['vmalert:8880']
    scrape_interval: 30s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s

  # SNMP 设备监控 (动态配置)
  - job_name: 'snmp-devices'
    static_configs: []
    # 这里会通过 MIB Platform 动态生成配置
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116