# VMAlert 告警规则配置
# 监控系统核心组件的健康状态和性能指标

groups:
  - name: monitoring.rules
    interval: 30s
    rules:
      # 服务可用性告警
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          category: availability
        annotations:
          summary: "服务 {{ $labels.job }} 不可用"
          description: "服务 {{ $labels.job }} 在实例 {{ $labels.instance }} 上已经停止运行超过1分钟"

      # VictoriaMetrics 相关告警
      - alert: VictoriaMetricsHighMemoryUsage
        expr: (vm_memory_usage_bytes / vm_available_memory_bytes) * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "VictoriaMetrics 内存使用率过高"
          description: "VictoriaMetrics 内存使用率为 {{ $value }}%，超过80%阈值"

      - alert: VictoriaMetricsHighDiskUsage
        expr: (vm_data_size_bytes / vm_free_disk_space_bytes) * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: storage
        annotations:
          summary: "VictoriaMetrics 磁盘使用率过高"
          description: "VictoriaMetrics 磁盘使用率为 {{ $value }}%，超过85%阈值"

      - alert: VictoriaMetricsSlowQueries
        expr: vm_slow_queries_total > 10
        for: 2m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "VictoriaMetrics 慢查询过多"
          description: "VictoriaMetrics 慢查询数量为 {{ $value }}，可能影响查询性能"

      # 系统资源告警
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "CPU 使用率过高"
          description: "实例 {{ $labels.instance }} CPU使用率为 {{ $value }}%，超过80%阈值"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "内存使用率过高"
          description: "实例 {{ $labels.instance }} 内存使用率为 {{ $value }}%，超过85%阈值"

      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 90
        for: 5m
        labels:
          severity: critical
          category: system
        annotations:
          summary: "磁盘使用率过高"
          description: "实例 {{ $labels.instance }} 磁盘 {{ $labels.mountpoint }} 使用率为 {{ $value }}%，超过90%阈值"

      - alert: DiskSpaceWillFillIn4Hours
        expr: predict_linear(node_filesystem_avail_bytes{fstype!="tmpfs"}[1h], 4*3600) < 0
        for: 5m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "磁盘空间即将耗尽"
          description: "实例 {{ $labels.instance }} 磁盘 {{ $labels.mountpoint }} 预计在4小时内耗尽"

      # 网络相关告警
      - alert: HighNetworkTraffic
        expr: rate(node_network_receive_bytes_total[5m]) + rate(node_network_transmit_bytes_total[5m]) > 100*1024*1024
        for: 5m
        labels:
          severity: warning
          category: network
        annotations:
          summary: "网络流量过高"
          description: "实例 {{ $labels.instance }} 接口 {{ $labels.device }} 网络流量为 {{ $value | humanize }}B/s"

      # Grafana 相关告警
      - alert: GrafanaHighResponseTime
        expr: histogram_quantile(0.95, rate(grafana_http_request_duration_seconds_bucket[5m])) > 5
        for: 3m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "Grafana 响应时间过长"
          description: "Grafana 95%分位响应时间为 {{ $value }}秒，超过5秒阈值"

      # 数据采集相关告警
      - alert: VMAgentScrapeFailures
        expr: increase(vm_promscrape_scrapes_failed_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
          category: monitoring
        annotations:
          summary: "VMAgent 采集失败过多"
          description: "VMAgent 在过去5分钟内采集失败 {{ $value }} 次"

      - alert: VMAgentHighMemoryUsage
        expr: process_resident_memory_bytes{job="vmagent"} / 1024 / 1024 > 500
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "VMAgent 内存使用过高"
          description: "VMAgent 内存使用量为 {{ $value }}MB，超过500MB阈值"

      # 告警管理器相关告警
      - alert: AlertmanagerConfigReloadFailure
        expr: alertmanager_config_last_reload_successful == 0
        for: 1m
        labels:
          severity: warning
          category: configuration
        annotations:
          summary: "Alertmanager 配置重载失败"
          description: "Alertmanager 配置重载失败，请检查配置文件"

      - alert: AlertmanagerNotificationFailures
        expr: increase(alertmanager_notifications_failed_total[5m]) > 0
        for: 1m
        labels:
          severity: warning
          category: notification
        annotations:
          summary: "Alertmanager 通知发送失败"
          description: "Alertmanager 在过去5分钟内发送通知失败 {{ $value }} 次"

  # SNMP 设备监控告警
  - name: snmp.rules
    interval: 60s
    rules:
      - alert: SNMPDeviceDown
        expr: up{job="snmp-devices"} == 0
        for: 2m
        labels:
          severity: critical
          category: network
        annotations:
          summary: "SNMP 设备不可达"
          description: "SNMP 设备 {{ $labels.instance }} 无法访问超过2分钟"

      - alert: HighInterfaceUtilization
        expr: (
          rate(ifHCInOctets[5m]) * 8 / ifHighSpeed / 1000000
        ) * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: network
        annotations:
          summary: "接口利用率过高"
          description: "设备 {{ $labels.instance }} 接口 {{ $labels.ifDescr }} 利用率为 {{ $value }}%"

      - alert: InterfaceDown
        expr: ifOperStatus != 1
        for: 1m
        labels:
          severity: warning
          category: network
        annotations:
          summary: "接口状态异常"
          description: "设备 {{ $labels.instance }} 接口 {{ $labels.ifDescr }} 状态异常"