version: '3.8'

services:
  # 数据库服务
  postgres:
    image: postgres:15
    container_name: mib-postgres
    environment:
      POSTGRES_DB: mib_platform
      POSTGRES_USER: mib_user
      POSTGRES_PASSWORD: mib_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - monitoring

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: mib-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - monitoring

  # MIB Platform 后端
  mib-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mib-backend
    environment:
      - DATABASE_URL=postgres://mib_user:mib_password@postgres:5432/mib_platform?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - PROMETHEUS_URL=http://prometheus:9090
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./opt/monitoring:/opt/monitoring
      - snmp_mibs:/usr/share/snmp/mibs
    depends_on:
      - postgres
      - redis
    networks:
      - monitoring

  # MIB Platform 前端
  mib-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mib-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://mib-backend:8080/api/v1
    depends_on:
      - mib-backend
    networks:
      - monitoring

  # VictoriaMetrics 单机版
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    ports:
      - "8428:8428"
    volumes:
      - vm_data:/victoria-metrics-data
    command:
      - "--storageDataPath=/victoria-metrics-data"
      - "--httpListenAddr=:8428"
      - "--retentionPeriod=12"
    networks:
      - monitoring

  # VMAgent (数据采集)
  vmagent:
    image: victoriametrics/vmagent:latest
    container_name: vmagent
    ports:
      - "8429:8429"
    volumes:
      - ./monitoring/vmagent/prometheus.yml:/etc/prometheus/prometheus.yml
      - vmagent_data:/vmagentdata
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
      - "--httpListenAddr=:8429"
    depends_on:
      - victoriametrics
    networks:
      - monitoring

  # Prometheus SNMP Exporter
  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    ports:
      - "9116:9116"
    volumes:
      - ./opt/monitoring/config/snmp_exporter:/etc/snmp_exporter
    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"
    networks:
      - monitoring

  # Categraf (替代方案)
  categraf:
    image: flashcatcloud/categraf:latest
    container_name: categraf
    volumes:
      - ./opt/monitoring/config/categraf:/etc/categraf
    environment:
      - CAT_PROMETHEUS_REMOTE_WRITE_URL=http://victoriametrics:8428/api/v1/write
    depends_on:
      - victoriametrics
    networks:
      - monitoring

  # Node Exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - victoriametrics
    networks:
      - monitoring

  # VMAlert (告警管理)
  vmalert:
    image: victoriametrics/vmalert:latest
    container_name: vmalert
    ports:
      - "8880:8880"
    volumes:
      - ./monitoring/vmalert/rules:/etc/vmalert/rules
    command:
      - "--datasource.url=http://victoriametrics:8428"
      - "--notifier.url=http://alertmanager:9093"
      - "--rule=/etc/vmalert/rules/*.yml"
      - "--httpListenAddr=:8880"
    depends_on:
      - victoriametrics
      - alertmanager
    networks:
      - monitoring

  # Alertmanager
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    networks:
      - monitoring

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: mib-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./monitoring/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./monitoring/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - mib-frontend
      - mib-backend
      - grafana
    networks:
      - monitoring

volumes:
  postgres_data:
  redis_data:
  vm_data:
  vmagent_data:
  grafana_data:
  alertmanager_data:
  snmp_mibs:

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16