# VMAgent 配置文件
# 用于采集各种监控指标并发送到 VictoriaMetrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'mib-monitoring'
    replica: 'vmagent-01'

# 采集任务配置
scrape_configs:
  # VMAgent 自身监控
  - job_name: 'vmagent'
    static_configs:
      - targets: ['localhost:8429']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # VictoriaMetrics 监控
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Node Exporter 系统指标
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # SNMP Exporter 网络设备监控
  - job_name: 'snmp-exporter'
    static_configs:
      - targets: ['snmp-exporter:9116']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Grafana 监控
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Alertmanager 监控
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # VMAlert 监控
  - job_name: 'vmalert'
    static_configs:
      - targets: ['vmalert:8880']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Categraf 监控
  - job_name: 'categraf'
    static_configs:
      - targets: ['categraf:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Docker 容器监控（如果启用）
  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
        regex: '(.{12}).*'
        replacement: '${1}'

  # 自定义 SNMP 设备监控
  - job_name: 'snmp-devices'
    static_configs:
      - targets:
        # 在这里添加您的 SNMP 设备
        # - '192.168.1.1'  # 路由器
        # - '192.168.1.10' # 交换机
    metrics_path: /snmp
    params:
      module: [if_mib]  # 默认使用接口 MIB
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116

  # 自定义应用监控
  - job_name: 'custom-apps'
    static_configs:
      - targets:
        # 在这里添加您的应用程序监控端点
        # - 'app1:8080'
        # - 'app2:9090'
    scrape_interval: 15s
    metrics_path: '/metrics'