# Alertmanager 配置文件
# 告警通知路由和接收器配置

global:
  # SMTP 服务器配置（邮件通知）
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@your-domain.com'
  smtp_auth_username: 'alertmanager@your-domain.com'
  smtp_auth_password: 'your-email-password'
  smtp_require_tls: true
  
  # 全局标签
  smtp_hello: 'alertmanager'
  
  # 解析超时
  resolve_timeout: 5m

# 模板文件路径
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# 告警路由配置
route:
  # 默认接收器
  receiver: 'default-receiver'
  
  # 分组配置
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  
  # 子路由配置
  routes:
    # 严重告警立即通知
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
      continue: true
    
    # 系统相关告警
    - match:
        category: system
      receiver: 'system-alerts'
      group_interval: 5m
      repeat_interval: 30m
    
    # 网络设备告警
    - match:
        category: network
      receiver: 'network-alerts'
      group_interval: 2m
      repeat_interval: 15m
    
    # 性能相关告警
    - match:
        category: performance
      receiver: 'performance-alerts'
      group_interval: 5m
      repeat_interval: 1h
    
    # 监控系统自身告警
    - match:
        category: monitoring
      receiver: 'monitoring-alerts'
      group_interval: 1m
      repeat_interval: 10m

# 抑制规则
inhibit_rules:
  # 如果有严重告警，抑制相同实例的警告告警
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['instance']
  
  # 如果服务不可用，抑制该服务的其他告警
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['instance', 'job']

# 接收器配置
receivers:
  # 默认接收器
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@your-domain.com'
        subject: '[监控告警] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          实例: {{ .Labels.instance }}
          {{ end }}
    
    # Webhook 通知（可选）
    webhook_configs:
      - url: 'http://your-webhook-url/alerts'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'webhook-user'
            password: 'webhook-password'
  
  # 严重告警接收器
  - name: 'critical-alerts'
    email_configs:
      - to: 'critical-alerts@your-domain.com'
        subject: '[🚨严重告警] {{ .GroupLabels.alertname }}'
        body: |
          🚨 严重告警通知 🚨
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          实例: {{ .Labels.instance }}
          服务: {{ .Labels.job }}
          {{ end }}
          
          请立即处理！
    
    # 短信通知（需要配置短信网关）
    webhook_configs:
      - url: 'http://sms-gateway/send'
        send_resolved: true
  
  # 系统告警接收器
  - name: 'system-alerts'
    email_configs:
      - to: 'system-admin@your-domain.com'
        subject: '[系统告警] {{ .GroupLabels.alertname }}'
        body: |
          系统告警通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          实例: {{ .Labels.instance }}
          {{ end }}
  
  # 网络告警接收器
  - name: 'network-alerts'
    email_configs:
      - to: 'network-admin@your-domain.com'
        subject: '[网络告警] {{ .GroupLabels.alertname }}'
        body: |
          网络设备告警通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          设备: {{ .Labels.instance }}
          {{ end }}
  
  # 性能告警接收器
  - name: 'performance-alerts'
    email_configs:
      - to: 'performance-team@your-domain.com'
        subject: '[性能告警] {{ .GroupLabels.alertname }}'
        body: |
          性能告警通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          实例: {{ .Labels.instance }}
          当前值: {{ .Annotations.value }}
          {{ end }}
  
  # 监控系统告警接收器
  - name: 'monitoring-alerts'
    email_configs:
      - to: 'monitoring-team@your-domain.com'
        subject: '[监控系统告警] {{ .GroupLabels.alertname }}'
        body: |
          监控系统告警通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          组件: {{ .Labels.job }}
          实例: {{ .Labels.instance }}
          {{ end }}