# SNMP Exporter 配置文件
# 网络设备监控配置

# 通用网络设备模块
modules:
  # 通用 SNMP v2c 配置
  if_mib:
    walk:
      - 1.3.6.1.2.1.2.2.1.2   # ifDescr
      - 1.3.6.1.2.1.2.2.1.3   # ifType
      - 1.3.6.1.2.1.2.2.1.5   # ifSpeed
      - 1.3.6.1.2.1.2.2.1.7   # ifAdminStatus
      - 1.3.6.1.2.1.2.2.1.8   # ifOperStatus
      - 1.3.6.1.2.1.2.2.1.10  # ifInOctets
      - 1.3.6.1.2.1.2.2.1.11  # ifInUcastPkts
      - 1.3.6.1.2.1.2.2.1.12  # ifInNUcastPkts
      - 1.3.6.1.2.1.2.2.1.13  # ifInDiscards
      - 1.3.6.1.2.1.2.2.1.14  # ifInErrors
      - 1.3.6.1.2.1.2.2.1.16  # ifOutOctets
      - 1.3.6.1.2.1.2.2.1.17  # ifOutUcastPkts
      - 1.3.6.1.2.1.2.2.1.18  # ifOutNUcastPkts
      - 1.3.6.1.2.1.2.2.1.19  # ifOutDiscards
      - 1.3.6.1.2.1.2.2.1.20  # ifOutErrors
    version: 2
    auth:
      community: public
    lookups:
      - source_indexes: [ifIndex]
        lookup: 1.3.6.1.2.1.2.2.1.2
        drop_source_indexes: false
    overrides:
      ifAdminStatus:
        type: EnumAsInfo
      ifOperStatus:
        type: EnumAsInfo
      ifType:
        type: EnumAsInfo

  # 系统信息模块
  system:
    walk:
      - 1.3.6.1.2.1.1.1.0     # sysDescr
      - 1.3.6.1.2.1.1.2.0     # sysObjectID
      - 1.3.6.1.2.1.1.3.0     # sysUpTime
      - 1.3.6.1.2.1.1.4.0     # sysContact
      - 1.3.6.1.2.1.1.5.0     # sysName
      - 1.3.6.1.2.1.1.6.0     # sysLocation
    version: 2
    auth:
      community: public

  # 主机资源监控
  host:
    walk:
      - 1.3.6.1.2.1.25.1.1.0  # hrSystemUptime
      - 1.3.6.1.2.1.25.2.2    # hrStorageTable
      - 1.3.6.1.2.1.25.3.2    # hrProcessorTable
      - 1.3.6.1.2.1.25.3.3    # hrNetworkTable
    version: 2
    auth:
      community: public
    lookups:
      - source_indexes: [hrStorageIndex]
        lookup: 1.3.6.1.2.1.25.2.3.1.3
        drop_source_indexes: false
      - source_indexes: [hrProcessorFrwID]
        lookup: 1.3.6.1.2.1.25.3.3.1.1
        drop_source_indexes: false

  # Cisco 设备专用模块
  cisco:
    walk:
      - 1.3.6.1.2.1.2.2.1     # ifTable
      - 1.3.6.1.4.1.9.9.109.1.1.1.1.3  # cpmCPUTotal5min
      - 1.3.6.1.4.1.9.9.109.1.1.1.1.4  # cpmCPUTotal1min
      - 1.3.6.1.4.1.9.9.109.1.1.1.1.5  # cpmCPUTotal5sec
      - 1.3.6.1.4.1.9.9.48.1.1.1       # ciscoMemoryPoolTable
    version: 2
    auth:
      community: public
    lookups:
      - source_indexes: [ifIndex]
        lookup: 1.3.6.1.2.1.2.2.1.2
        drop_source_indexes: false
      - source_indexes: [ciscoMemoryPoolType]
        lookup: 1.3.6.1.4.1.9.9.48.1.1.1.2
        drop_source_indexes: false

  # HP/HPE 设备模块
  hp:
    walk:
      - 1.3.6.1.2.1.2.2.1     # ifTable
      - 1.3.6.1.4.1.11.2.14.11.5.1.9.6.1.0  # hpSwitchCpuStat
      - 1.3.6.1.4.1.11.2.14.11.5.1.1.2.1.1  # hpSwitchPortTable
    version: 2
    auth:
      community: public

  # Huawei 设备模块
  huawei:
    walk:
      - 1.3.6.1.2.1.2.2.1     # ifTable
      - 1.3.6.1.4.1.2011.5.25.31.1.1.1.1.5  # hwEntityCpuUsage
      - 1.3.6.1.4.1.2011.5.25.31.1.1.1.1.7  # hwEntityMemUsage
    version: 2
    auth:
      community: public

  # UPS 设备模块
  ups:
    walk:
      - 1.3.6.1.2.1.33.1.1    # upsIdent
      - 1.3.6.1.2.1.33.1.2    # upsBattery
      - 1.3.6.1.2.1.33.1.3    # upsInput
      - 1.3.6.1.2.1.33.1.4    # upsOutput
      - 1.3.6.1.2.1.33.1.5    # upsBypass
      - 1.3.6.1.2.1.33.1.7    # upsAlarm
    version: 2
    auth:
      community: public

  # 打印机设备模块
  printer:
    walk:
      - 1.3.6.1.2.1.25.3.2.1.3   # hrPrinterStatus
      - 1.3.6.1.2.1.43.5.1.1     # prtMarkerSuppliesTable
      - 1.3.6.1.2.1.43.8.2.1     # prtInputTable
      - 1.3.6.1.2.1.43.9.2.1     # prtOutputTable
    version: 2
    auth:
      community: public

  # Windows 服务器模块
  windows:
    walk:
      - 1.3.6.1.2.1.25.1.1.0     # hrSystemUptime
      - 1.3.6.1.2.1.25.2.2       # hrStorageTable
      - 1.3.6.1.2.1.25.3.3.1.2   # hrProcessorLoad
      - 1.3.6.1.4.1.311.1.1.3.1.1.1.1.1  # Windows CPU
    version: 2
    auth:
      community: public

  # Linux 服务器模块
  linux:
    walk:
      - 1.3.6.1.4.1.2021.4       # memory
      - 1.3.6.1.4.1.2021.10      # laTable
      - 1.3.6.1.4.1.2021.11      # systemStats
      - 1.3.6.1.4.1.2021.9.1     # dskTable
    version: 2
    auth:
      community: public

  # SNMP v3 安全模块示例
  secure_device:
    walk:
      - 1.3.6.1.2.1.1
      - 1.3.6.1.2.1.2.2.1
    version: 3
    auth:
      username: monitoring_user
      security_level: authPriv
      password: auth_password
      auth_protocol: SHA
      priv_password: priv_password
      priv_protocol: AES

  # 自定义设备模块模板
  custom_device:
    walk:
      - 1.3.6.1.2.1.1           # System group
      - 1.3.6.1.2.1.2.2.1       # Interface table
      # 添加您的自定义 OID
    version: 2
    auth:
      community: public
    # 自定义查找表
    lookups:
      - source_indexes: [ifIndex]
        lookup: 1.3.6.1.2.1.2.2.1.2
        drop_source_indexes: false
    # 自定义覆盖
    overrides:
      ifOperStatus:
        type: EnumAsInfo