apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "30s"
      queryTimeout: "60s"
      httpMethod: "POST"
    version: 1

  - name: MIB Platform
    type: postgres
    access: proxy
    url: postgres:5432
    database: mib_platform
    user: mib_user
    secureJsonData:
      password: mib_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    version: 1